# Generated by Django 2.0.1 on 2018-04-07 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Citymaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtitle', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('rid', models.IntegerField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=45)),
                ('lastname', models.CharField(blank=True, max_length=45)),
                ('parentname', models.CharField(blank=True, max_length=45)),
                ('dateofbirth', models.DateField(blank=True, null=True)),
                ('mobileno', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=2)),
                ('basicsalary', models.IntegerField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duradiff.Citymaster')),
                ('jobtitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duradiff.Qualification')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duradiff.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('pfamt', models.IntegerField()),
                ('esiamt', models.IntegerField()),
                ('totalOThours', models.IntegerField()),
                ('netsalary', models.IntegerField()),
                ('netbasic', models.IntegerField()),
                ('totalOTamt', models.IntegerField()),
                ('totalpaybl', models.IntegerField()),
                ('netpaybl', models.IntegerField()),
                ('miscellaneous', models.IntegerField()),
                ('conveyance', models.IntegerField()),
                ('totalabsent', models.IntegerField()),
                ('absencededuction', models.IntegerField()),
                ('rid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duradiff.Resource')),
            ],
        ),
        migrations.CreateModel(
            name='Statemaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theday', models.DateField(blank=True, null=True)),
                ('timeinhr', models.TimeField(verbose_name='%H:%M')),
                ('timeouthr', models.TimeField(verbose_name='%H:%M')),
                ('delta', models.DurationField(blank=True, null=True)),
                ('hrsworked', models.DecimalField(decimal_places=2, max_digits=2)),
                ('OT', models.DecimalField(decimal_places=2, max_digits=2)),
                ('absent', models.BooleanField(default=False)),
                ('specialday', models.BooleanField(default=False)),
                ('rid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duradiff.Resource')),
            ],
        ),
        migrations.AddField(
            model_name='resource',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duradiff.Statemaster'),
        ),
    ]
