# Generated by Django 2.0.1 on 2018-04-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duradiff', '0004_auto_20180408_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='timeinhr',
            field=models.TimeField(blank=True, null=True, verbose_name='%H:%M'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='timeouthr',
            field=models.TimeField(blank=True, null=True, verbose_name='%H:%M'),
        ),
    ]
