# Generated by Django 2.0.1 on 2018-04-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duradiff', '0008_auto_20180413_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='absencededuction',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='esiamt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='netpaybl',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='totalOTamt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='totalpaybl',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
