# Generated by Django 2.0.4 on 2018-04-21 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('duradiff', '0010_auto_20180414_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='citymaster',
            name='state',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='duradiff.Statemaster'),
        ),
    ]
