# Generated by Django 2.0.4 on 2018-04-21 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duradiff', '0011_citymaster_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timesheet',
            old_name='specialday',
            new_name='fullOTday',
        ),
    ]
