# Generated by Django 2.0.4 on 2018-04-22 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duradiff', '0012_auto_20180421_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='pfamt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
