# Generated by Django 2.0.4 on 2018-04-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duradiff', '0013_auto_20180422_0912'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='citymaster',
            options={'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='salary',
            options={'verbose_name_plural': 'Salaries'},
        ),
        migrations.AlterModelOptions(
            name='statemaster',
            options={'verbose_name_plural': 'States'},
        ),
        migrations.AlterField(
            model_name='salary',
            name='absencededuction',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='absence deduction'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='conveyance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='esiamt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='ESI amt'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='miscellaneous',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='pfamt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='PF amt'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='totalOThours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='totalabsent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
