# Generated by Django 2.0.4 on 2018-04-28 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duradiff', '0015_salary_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timesheet',
            unique_together={('rid', 'theday')},
        ),
    ]
