# Generated by Django 2.0.4 on 2018-05-03 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duradiff', '0016_auto_20180428_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='ESIno',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AddField(
            model_name='resource',
            name='UAN',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AddField(
            model_name='resource',
            name='shifthrs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
