# Generated by Django 2.0.4 on 2018-05-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duradiff', '0017_auto_20180503_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='Remarks',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='salary',
            name='shiftpenalty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='ridshifthrs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='shiftshortfall',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
