# Generated by Django 2.0.5 on 2018-05-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duradiff', '0019_resource_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='data',
        ),
        migrations.AddField(
            model_name='resource',
            name='Approvalnote',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
