# Generated by Django 2.0.5 on 2018-09-17 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duradiff', '0020_auto_20180529_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='splallowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Special Allowance'),
        ),
    ]
