# Generated by Django 2.1.1 on 2018-10-02 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duradiff', '0022_timesheet_endday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='miscellaneous',
        ),
    ]
