# Generated by Django 2.1.2 on 2019-01-06 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('duradiff', '0026_auto_20181004_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dept', models.CharField(max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='resource',
            name='Approvalnote',
        ),
        migrations.AddField(
            model_name='resource',
            name='Dept',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='duradiff.Department'),
        ),
    ]
