# Generated by Django 2.1.2 on 2019-01-06 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('duradiff', '0027_auto_20190106_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='Dept',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='duradiff.Department'),
        ),
    ]
