# Generated by Django 2.1.2 on 2019-01-06 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('duradiff', '0028_auto_20190106_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='Dept',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='duradiff.Department'),
        ),
    ]
